**Libraries**

In [2]:
from pydoc import help  # can type in the python console `help(name of function)` to get the documentation
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import scale
from sklearn.decomposition import PCA
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from scipy import stats
from IPython.display import display, HTML

# figures inline in notebook
%matplotlib inline

np.set_printoptions(suppress=True)

DISPLAY_MAX_ROWS = 20  # number of max rows to print for a DataFrame
pd.set_option('display.max_rows', DISPLAY_MAX_ROWS)

In [3]:
#python console

# %qtconsole

In [4]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
# creating initial dataframe
bridge_types = ('Arch','Beam','Truss','Cantilever','Tied Arch','Suspension','Cable')
bridge_df = pd.DataFrame(bridge_types, columns=['Bridge_Types'])
# creating instance of labelencoder
labelencoder = LabelEncoder()
# Assigning numerical values and storing in another column
bridge_df['Bridge_Types_Cat'] = labelencoder.fit_transform(bridge_df['Bridge_Types'])
bridge_df

  Bridge_Types  Bridge_Types_Cat
0         Arch                 0
1         Beam                 1
2        Truss                 6
3   Cantilever                 3
4    Tied Arch                 5
5   Suspension                 4
6        Cable                 2

In [75]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder

data = pd.read_excel('business_survey_results.xlsx', sheet_name='results', usecols=['2. Η Νομική μορφή της επιχείρησης είναι:', '6.1.1 Κύρια Δραστηριότητα', '7. Πόσο διαφοροποιημένα είναι τα προϊόντα που παράγει η επιχείρηση σε σχέση με τον ανταγωνισμό;', '1ος Στόχος', 'Πιστοποίηση των προϊόντων τους', 'Οι σχέσεις με τους πελάτες και η πιστωτική πολιτική έναντι των πελατών'])
data.columns = ["V"+str(i) for i in range(1, len(data.columns)+1)]  # rename column names

X = data.loc[:, "V2":]  # independent variables data

y = data.V1  # dependednt variable data
data.dtypes
data = data.fillna(data.mean()) 
for col_name in data.columns:
    if(data[col_name].dtype == 'object'):
        data[col_name]= data[col_name].astype('category')
        #data[col_name] = data[col_name].cat.codes
        #data = data.fillna(data.mean()) 
data

,V1,V2,V3,V4,V5
0,Ατομική Επιχείρηση,Ελαφρά διαφοροποιημένα σε σχέση με τον ανταγων...,Η κάλυψη των υποχρεώσεων,Μερικές φορές (3),Σε πολύ μεγάλο βαθμό
1,Ατομική Επιχείρηση,Αρκετά διαφοροποιημένα σε σχέση με τον ανταγων...,Η επιβίωση,Σπάνια (2),Σε κάποιο βαθμό
2,Ατομική Επιχείρηση,Ίδια με τον ανταγωνισμό,Η επιβίωση,Σπάνια (2),Σε σημαντικό βαθμό
3,ΟΕ,Ίδια με τον ανταγωνισμό,Η διατήρηση του μεριδίου που έχει στην αγορά,Πολύ συχνά (4),Σε κάποιο βαθμό
4,ΟΕ,Ελαφρά διαφοροποιημένα σε σχέση με τον ανταγων...,Η αύξηση του μεριδίου και η απόκτηση νέων πελατών,Σπάνια (2),Σε σημαντικό βαθμό
...,...,...,...,...,...
238,ΑΕ,Ελαφρά διαφοροποιημένα σε σχέση με τον ανταγων...,Η κάλυψη των υποχρεώσεων,Πολύ συχνά (4),Σε πολύ μεγάλο βαθμό
239,ΙΚΕ,Ίδια με τον ανταγωνισμό,Η διατήρηση του προσωπικού,Σπάνια (2),Σε πολύ μεγάλο βαθμό
240,ΟΕ,Ίδια με τον ανταγωνισμό,Η επιβίωση,Πάντα (5),Σε πολύ μεγάλο βαθμό
241,Άλλη μορφή,Πολύ διαφοροποιημένα σε σχέση με τον ανταγωνισμό,NaN,Πολύ συχνά (4),Σε πολύ μεγάλο βαθμό
242,ΑΕ,Ελαφρά διαφοροποιημένα σε σχέση με τον ανταγων...,Η αύξηση του μεριδίου και η απόκτηση νέων πελατών,Μερικές φορές (3),Σε σημαντικό βαθμό

In [68]:
df = data
pd.DataFrame({col: df[col].astype('category').cat.codes for col in df}, index=df.index)

     V1  V2  V3  V4  V5  V6
0     3   2   3   7   1   3
1     3   0   2   5   5   2
2     3  19   1   5   5   4
3     6  20   1   2   3   2
4     6  27   3   1   5   4
..   ..  ..  ..  ..  ..  ..
238   2  19   3   7   3   3
239   5   1   1   3   5   3
240   6   3   1   5   2   3
241   1   9   4   0   3   3
242   2  19   3   1   1   4

[243 rows x 6 columns]

In [63]:
data = data.stack().astype('category').cat.codes.unstack() #categorical to num
data = data.fillna(data.mean()) #replace NaN values with mean()
data

     V1  V2  V3  V4  V5  V6
0    42   2  45  53  57  66
1    42   0  40  51  69  65
2    42  19  38  51  69  68
3    58  20  38  47  63  65
4    58  27  45  46  69  68
..   ..  ..  ..  ..  ..  ..
238  39  19  45  53  63  66
239  56   1  38  48  69  66
240  58   3  38  51  59  66
241  37   9  60  50  63  66
242  39  19  45  46  57  68

[243 rows x 6 columns]

In [52]:

#from sklearn.preprocessing import LabelEncoder

# creating instance of labelencoder
#labelencoder = LabelEncoder()
# Assigning numerical values and storing in another column

#df = data.V1
#df.apply(LabelEncoder().fit_transform)

In [53]:
#from sklearn.preprocessing import LabelEncoder
#df = data
#le = LabelEncoder()
#le.fit(pd.concat([df.V1, df.V3]).unique()) # or np.unique(df.values.reshape(-1,1))

#df.apply(le.transform)

In [69]:
from sklearn.preprocessing import LabelEncoder
encoder_dict = defaultdict(LabelEncoder)
df = data
labeled_df = df.apply(lambda x: encoder_dict[x.name].fit_transform(x))

NameError: name 'defaultdict' is not defined

In [76]:
from sklearn.preprocessing import LabelEncoder
df = data
data = data.apply(LabelEncoder().fit_transform)
data

TypeError: Encoders require their input to be uniformly strings or numbers. Got ['float', 'str']